name: Unit Test
on: [push]
jobs:
  on_build_options:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE
          python -m pip install --upgrade pip
          python -m pip install --upgrade Pillow
      - name: Run tests
        run:
          python -m unittest tests/*.py